### ISSUE TITLE
Lista 6- tablice jednowymiarowe rząd B

### ISSUE THREAD

**Issue by kowalowy1234** [kowalowy1234/PS156036#6]
Spr
Zadanie 4_2_8 spełnia warunki kompilacji, ale nie potrafiłem rozwiązać problemu, przez który wartości tablicy się nie zmieniają. Podejrzewałem, że był to problem z różnicą w typach danych pomiędzy tablicami, jako iż w innych zadaniach nie było problemu ze zmianą wartości przy int-int, ale po konwersji nadal nic się nie zmieniło.

**Comment by pjastr** [comment]
4.2.1. - dla mnie zadanie jest poprawne, ale utrwala złe praktyki programistyczne. W momencie kiedy przekazujemy do funkcji tablicę (czyli wskaźnik na pierwszy element), nie musimy tej tablicy wyrzucać. Typ zwracany powinien być `void`.
4.2.6 - kilka błędów 
1) linijka 4 i 23 - za dużo wskaźników i adresów naraz
2) linijka 11 - typ drugiego parametru funkcji powinna być tablica `double`

moje rozwiązania:

```c
#include <stdio.h>
#include <stdlib.h>

void fun_a(int n, int *tab1, int *tab2, double *tab3){
    for(int i=0; i<n; i++){
        tab3[i]=tab1[i];
        tab3[i+n]=tab2[i];
    }
}

void wypisz(int n, double tab[]){
    for(int i=0; i<n; i++)
        printf("%f\t", tab[i]);
    printf("\n");
}

int main()
{
    int n=5;
    int tab1[]={4, 3, 1, 6, 4};
    int tab2[]={4, 1, 6, 4, 8};
    double tab3[2*n];
    fun_a(n, tab1, tab2, tab3);
    wypisz(n*2, tab3);
}
```

2 pkt
